---
- hosts: all
  become: yes

  tasks:
  - name: OS & Distribution related info
    debug:
      var: '{{ item }}'
    with_items:
    - ansible_os_family
    - ansible_distribution
    - ansible_distribution_version
    - ansible_distribution_major_version
    - ansible_distribution_minor_version

  - name: Install tools
    package:
      name: vim
      state: present

  - name: Deploy TLS Certificates
    import_role:
      name: andrewrothstein.pki
    vars:
      pki_self_sign: True
      pki_dir: /root/pki
      pki_names:
        - C: US
          L: Nashua
          O: Example
          OU: Demo
          ST: 'New Hampshire'
      pki_ca:
        cname: 'Example Root Certificate Authority'
        expiry: '87600h'
        pathlen: 0
      pki_servers:
        - cname: allthethings.example.com
          include_localhost: True
          profile: server
          sans:
            - allthethings.example.com
            - allthethings

  - name: Install 389 Directory Server
    import_role:
      name: lvps.389ds_server
    vars:
      dirsrv_rootdn_password: '{{ admin_password }}'

  - name: Install postgresql
    import_role:
      name: geerlingguy.postgresql

  - name: Create gitea db user
    become_user: postgres
    postgresql_user:
      name: gitea
      password: '{{ db_password }}'

  - name: Create gitea database
    become_user: postgres
    postgresql_db:
      name: giteadb
      owner: gitea

  - name: Install gitea
    import_role:
      name: do1jlr.gitea
    vars:
      gitea_http_listen: 0.0.0.0
      gitea_http_port: 3001
      gitea_disable_registration: true
      gitea_db_type: postgres
      gitea_db_host: localhost:5432
      gitea_db_name: giteadb
      gitea_db_user: gitea
      gitea_db_password: '{{ db_password }}'

  - name: wait for gitea to come up
    uri:
      url: "http://127.0.0.1:3001"
      status_code: 200
    register: result
    until: result.status == 200
    retries: 60
    delay: 1

  - name: Check for gitea admin user
    shell: /usr/local/bin/gitea -c /etc/gitea/gitea.ini --custom-path /var/lib/gitea/custom/ admin user list | grep ^1
    register: giteaadmin
    changed_when: false
    failed_when: false

  - name: Create admin user
    command: /usr/local/bin/gitea -c /etc/gitea/gitea.ini --custom-path /var/lib/gitea/custom/ admin user create --username gitadmin --password '{{ admin_password }}' --admin --email root@localhost
    when: giteaadmin.rc != 0

  - name: Add gitea to firewall
    firewalld:
      port: 3001/tcp
      permanent: yes
      immediate: yes
      state: enabled

  - name: Install nodejs
    import_role:
      name: geerlingguy.nodejs

  - name: Create wikijs db user
    become_user: postgres
    postgresql_user:
      name: wikijs
      password: '{{ db_password }}'

  - name: Create wikijs database
    become_user: postgres
    postgresql_db:
      name: wikijsdb
      owner: gitea

  - name: Install wikijs
    import_role:
      name: supertarto.wikijs
    vars:
      wikijs_download_dest: /opt/wikijs
      wikijs_config_port: 3002
      wikijs_config_db_type: postgres
      wikijs_config_db_host: localhost
      wikijs_config_db_port: 5432
      wikijs_config_db_user: wikijs
      wikijs_config_db_pass: '{{ db_password }}'
      wikijs_config_db_db: wikijsdb
      wikijs_config_db_ssl: false

  - name: Add wikijs to firewall
    firewalld:
      port: 3002/tcp
      permanent: yes
      immediate: yes
      state: enabled
