---
roles:
  - name: andrewrothstein.pki
  - name: lvps.389ds_server
  - name: geerlingguy.postgresql
  - name: do1jlr.gitea
  - name: geerlingguy.nodejs
  - name: uoi-io.haproxy

collections:
  - name: nginxinc.nginx_core
